/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {
    Employee employee = new Employee("Abdullah", 23, 42938443, 329384930, new Address("Al-Nahda"));
    employee.print();

    Employee employee2 = new Employee("Sultan", 20, 49938443, 379384930, new Address("Somewhere"));
    employee2.print();

    Employee employee3 = new Employee("Ali", 15, 50938443, 379384931, new Address("Somewhere"));
    employee3.print();

    System.out.println("==================");

    // professional
    Bank bank = new Bank("9387498273", 20000, "Neighborhood");

    Bank bank2 = new Bank("9287498273", 10000, "Debit");
    Bank bank3 = new Bank("9487498273", 40000, "iknownothingaboutbanksaccounttype");

  }
}
